server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springsecurity
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: ALWAYS



